In [30]:
import cv2

In [39]:
img_g = cv2.imread("images/smallgray.png",0)
print(img_g)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [40]:
cv2.imwrite("newsmallgray.png",img_g)

True

In [43]:
img_g[0:2,2:4]

array([[104, 121],
       [255, 255]], dtype=uint8)

In [45]:
img_g.shape

(3, 5)

In [51]:
for i in img_g:
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [53]:
for i in img_g.flat:
    print(i)

187
158
104
121
143
198
125
255
255
147
209
134
255
97
182


In [55]:
img_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [62]:
ims = numpy.hstack((img_g,img_g))
print(ims)

[[187 158 104 121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182]]


In [64]:
ims = numpy.vstack((img_g,img_g))
print(ims)

[[187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]
 [187 158 104 121 143]
 [198 125 255 255 147]
 [209 134 255  97 182]]


In [74]:
lst = numpy.vsplit(ims,3)

TypeError: 'type' object is not subscriptable